import type { Dua, DuaCategory } from './types'

// Default categories
export const DEFAULT_CATEGORIES: DuaCategory[] = [
  { _id: '1', name: 'Morning & Evening', nameArabic: 'أدعية الصباح والمساء' },
  { _id: '2', name: 'Before & After Prayer', nameArabic: 'أدعية قبل وبعد الصلاة' },
  { _id: '3', name: 'Daily Duas', nameArabic: 'أدعية يومية' },
  { _id: '4', name: 'Travel', nameArabic: 'أدعية السفر' },
  { _id: '5', name: 'Food & Drink', nameArabic: 'أدعية الطعام والشراب' },
  { _id: '6', name: 'Sleep & Waking', nameArabic: 'أدعية النوم والاستيقاظ' },
  { _id: '7', name: 'Health & Sickness', nameArabic: 'أدعية الصحة والمرض' },
  { _id: '8', name: 'Protection', nameArabic: 'أدعية الحماية' },
  { _id: '9', name: 'Forgiveness', nameArabic: 'أدعية الاستغفار' },
  { _id: '10', name: 'Guidance', nameArabic: 'أدعية الهداية' },
]

// Sample duas as fallback data
export const SAMPLE_DUAS: Dua[] = [
  {
    _id: '1',
    title: 'Dua before sleeping',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismika Allahumma amootu wa ahya',
    translation: 'In Your name, O Allah, I die and I live',
    category: 'Sleep & Waking',
    categoryId: '6',
    reference: 'Sahih al-Bukhari 6324',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    isActive: true,
  },
  {
    _id: '2',
    title: 'Dua upon waking up',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: "Alhamdulillahil-lathee ahyana ba'da ma amatana wa ilayhin-nushoor",
    translation: 'All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection',
    category: 'Sleep & Waking',
    categoryId: '6',
    reference: 'Sahih al-Bukhari 6312',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '3',
    title: 'Dua before eating',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah',
    translation: 'In the name of Allah',
    category: 'Food & Drink',
    categoryId: '5',
    reference: 'Sahih al-Bukhari 5376',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '4',
    title: 'Dua after eating',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    transliteration: "Alhamdulillahil-lathee at'amana wa saqana wa ja'alana muslimeen",
    translation: 'All praise is for Allah who fed us and gave us drink, and made us Muslims',
    category: 'Food & Drink',
    categoryId: '5',
    reference: 'Sunan Abi Dawud 3850',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '5',
    title: 'Dua when entering home',
    arabic: 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى رَبِّنَا تَوَكَّلْنَا',
    transliteration: "Bismillahi walajna, wa bismillahi kharajna, wa 'ala rabbina tawakkalna",
    translation: 'In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we depend',
    category: 'Daily Duas',
    categoryId: '3',
    reference: 'Sunan Abi Dawud 5096',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '6',
    title: 'Dua when leaving home',
    arabic: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: "Bismillahi, tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
    translation: 'In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah',
    category: 'Daily Duas',
    categoryId: '3',
    reference: 'Sunan Abi Dawud 5095',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '7',
    title: 'Dua for traveling',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
    transliteration: 'Subhanal-lathee sakhkhara lana hadha wa ma kunna lahu muqrineen, wa inna ila rabbina lamunqaliboon',
    translation: 'Glory to Him who has subjected this to us, and we could never have it (by our efforts). And verily, to Our Lord we indeed are to return',
    category: 'Travel',
    categoryId: '4',
    reference: 'Surah Az-Zukhruf 43:13-14',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '8',
    title: 'Dua for protection from evil',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    transliteration: "A'oodhu bi kalimatil-lahit-tammati min sharri ma khalaq",
    translation: 'I seek refuge in the perfect words of Allah from the evil of what He has created',
    category: 'Protection',
    categoryId: '8',
    reference: 'Sahih Muslim 2708',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '9',
    title: 'Dua for seeking forgiveness',
    arabic: 'رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ',
    transliteration: "Rabbi ighfir lee wa tub 'alayya innaka antat-tawwabur-raheem",
    translation: 'My Lord, forgive me and accept my repentance, for You are the Accepter of Repentance, the Most Merciful',
    category: 'Forgiveness',
    categoryId: '9',
    reference: 'Sahih al-Bukhari 6307',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '10',
    title: 'Dua for guidance',
    arabic: 'اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ',
    transliteration: "Allahumma-hdini feeman hadayt, wa 'afini feeman 'afayt, wa tawallani feeman tawallayt",
    translation: 'O Allah, guide me among those You have guided, grant me health among those You have granted health, and befriend me among those You have befriended',
    category: 'Guidance',
    categoryId: '10',
    reference: 'Sunan Abi Dawud 760',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '11',
    title: 'Morning remembrance',
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ',
    transliteration: 'Asbahna wa asbahal-mulku lillah, walhamdulillah, la ilaha illallah',
    translation: 'We have reached the morning and at this very time all dominion belongs to Allah, and all praise is for Allah. None has the right to be worshipped except Allah',
    category: 'Morning & Evening',
    categoryId: '1',
    reference: 'Sahih Muslim 2723',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
  {
    _id: '12',
    title: 'Evening remembrance',
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ',
    transliteration: 'Amsayna wa amsal-mulku lillah, walhamdulillah, la ilaha illallah',
    translation: 'We have reached the evening and at this very time all dominion belongs to Allah, and all praise is for Allah. None has the right to be worshipped except Allah',
    category: 'Morning & Evening',
    categoryId: '1',
    reference: 'Sahih Muslim 2723',
    createdAt: new Date(),
    updatedAt: new Date(),
    isActive: true,
  },
]

